### ISSUE TITLE
Cannot open project

### ISSUE THREAD

**Issue by dogadogan** [Orinion/RaycastTest#1]
Hi,

I'm getting these errors, while trying the open the project in Unity, any idea why? :(

```
An error occurred while resolving packages:
Project has invalid dependencies:
com.meta.xr.depthapi: Error when executing git command. 2024-03-22 12:15:29.014 xcodebuild[5841:141967] [MT] DVTPlugInLoading: Failed to load code for plug-in com.apple.dt.dbg.DebuggerFoundation (/Applications/Xcode.app/Contents/PlugIns/DebuggerFoundation.ideplugin), error = Error Domain=NSCocoaErrorDomain Code=3588 "dlopen(/Applications/Xcode.app/Contents/PlugIns/DebuggerFoundation.ideplugin/Contents/MacOS/DebuggerFoundatio...

(For the full error message, see the editor log file located at [/Users/dogadogan/Library/Logs/Unity/Editor.log])


Fatal Error!
GetManagerFromContext: pointer to object of manager 'MonoManager' is NULL (table index 5)

```

Thank you!

**Comment by Orinion** [comment]
> Failed to load code for plug-in com.apple.dt.dbg.DebuggerFoundation

Seems to be an Apple/Xcode specific issue, i couldn't reproduce it on Windows. Did you clone the project directly with Xcode? I would instead try downloading the project as a Zip file and then open it using Unity Hub. If that dosent work, setup a new unity project, add the DepthAPI and manually add the [Files](../tree/main/Assets/Raycast) and [SampleScene](../tree/main/Assets/Scenes).

**Comment by dogadogan** [comment]
Indeed, it was an Xcode issue. I had to install its new version :D Thanks for your help!
